prefix udm: <http://data.nxp.com/def/udm/>
PREFIX plm: <http://data.nxp.com/def/plm/>
SELECT *  
from <urn:dydra:all>
WHERE {
  ?s a udm:TestCentre .
  FILTER EXISTS {
  ?testflow a udm:TestFlow ; ?p ?s .
} }