
PREFIX plm: <http://data.nxp.com/def/plm/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX udm: <http://data.nxp.com/def/udm/>
 
SELECT DISTINCT ?g
WHERE {
  GRAPH ?g {
    ?s a ?type ;
       ?p ?o .
  }
  FILTER  EXISTS {
    GRAPH ?g_ECO {
      ?ECO a udm:ECO ;
           plm:changedItem ?s .
    }
  }
}
LIMIT 10