SELECT DISTINCT ?title ?children {GRAPH <http://qa.data.nexperia.com/id/projects/1519679733038> {OPTIONAL { <http://qa.data.nexperia.com/id/concepts/1519679784467> <http://www.w3.org/2004/02/skos/core#prefLabel> ?title . }} FILTER (lang(?title) = 'en' || !bound(?title)) BIND ( EXISTS { <http://qa.data.nexperia.com/id/concepts/1519679784467>  <http://www.w3.org/2004/02/skos/core#narrower> ?_narrow } AS ?children ) }