SELECT ?uri ?title ?children WHERE {GRAPH <http://www.data.nexperia.com/id/projects/1596470054838> {?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept>. MINUS {?_sub1 <http://www.w3.org/2004/02/skos/core#narrower> ?uri}. MINUS {?_sub2 <http://www.w3.org/2004/02/skos/core#hasTopConcept> ?uri}.OPTIONAL{ ?uri <http://www.w3.org/2004/02/skos/core#prefLabel> ?title. }} FILTER(lang(?title)='en' || !bound(?title)) BIND(EXISTS {?uri <http://www.w3.org/2004/02/skos/core#narrower> ?_narrow} AS ?children) } ORDER BY str(?title) str(?uri)