SELECT DISTINCT ?title ?children {GRAPH <http://www.data.nexperia.com/id/projects/marketingTree> {OPTIONAL { <http://www.data.nexperia.com/id/concepts/1449823551321> <http://www.w3.org/2004/02/skos/core#prefLabel> ?title . }} FILTER (lang(?title) = 'en-us' || !bound(?title)) BIND ( EXISTS { <http://www.data.nexperia.com/id/concepts/1449823551321>  <http://www.w3.org/2004/02/skos/core#narrower> ?_narrow } AS ?children ) }